apiVersion: apps/v1
kind: Deployment
metadata:
  name: agri-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agri-app
  template:
    metadata:
      labels:
        app: agri-app
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
    spec:
      containers:
      - name: agri-app
        image: fayzullayev7505/agri-app:v1
        ports:
        - containerPort: 5000
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: agri-app-service
spec:
  selector:
    app: agri-app
  ports:
    - name: web
      port: 80
      targetPort: 5000
    - name: metrics
      port: 8000
      targetPort: 8000
  type: LoadBalancer